# Generated by Django 4.2.6 on 2023-12-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
