# Generated by Django 4.2.6 on 2023-12-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
